### PR TITLE
Refs #9089 - port to refactored SSL verification

### PR DESCRIPTION
**Pull request by mmilata**
Introduced to smart-proxy in 0207401d84ddb5e4396157a38ad32a675f0e3e8f.

### CODE REVIEW

**Comment by mmilata** [comment]
@lzap does this look alright to you? I didn't test it yet because my foreman-nightly machine fell apart ...

**Comment by mmilata** [comment]
I've tested it now and it seems to work fine.

**Comment by lzap** [comment]
:+1:

**Comment by lzap** [comment]
One additional comment - this basically introduces incompatibility. Your plugin now requires Foreman 1.8. I recommend to bump the mayor version according to our plugin versioning guidelines.

**Comment by mmilata** [comment]
Right - I'll bump the major version when releasing new gem.

**Pull request merged**
